# Generated by Django 3.2 on 2022-04-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_friendy_name_category_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
